module.exports = {
	INCREMENT_COUNTER: 'INCREMENT_COUNTER',
	DECREMENT_COUNTER: 'DECREMENT_COUNTER',
	GET_APP_INDEX_MENU: 'GET_APP_INDEX_MENU',
	GET_ARCHIVES: 'GET_ARCHIVES',
	GET_ARCHIVES_ERROR: 'GET_ARCHIVES_ERROR',
}