module.exports = {
	INCREMENT_COUNTER: 'INCREMENT_COUNTER',
	DECREMENT_COUNTER: 'DECREMENT_COUNTER',
	GET_APP_INDEX_MENU: 'GET_APP_INDEX_MENU',
	GET_ARCHIVES: 'GET_ARCHIVES',
	SUBMIT_ARCHIVES: 'SUBMIT_ARCHIVES',
	SAVE_ARCHIVES: 'SAVE_ARCHIVES',
	LOGIN: 'LOGIN'
}